In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv("Popularity of Programming Languages from 2004 to 2023.csv")
data.head(10)

,Date,Abap,Ada,C/C++,C#,Cobol,Dart,Delphi/Pascal,Go,Groovy,...,Powershell,Python,R,Ruby,Rust,Scala,Swift,TypeScript,VBA,Visual Basic
0,July 2004,0.34,0.36,10.01,4.68,0.42,0.0,2.80,0.0,0.03,...,0.16,2.51,0.39,0.33,0.24,0.17,0.0,0.00,1.43,8.50
1,August 2004,0.35,0.36,9.74,4.96,0.46,0.0,2.65,0.0,0.07,...,0.15,2.62,0.40,0.40,0.19,0.17,0.0,0.00,1.45,8.51
2,September 2004,0.41,0.41,9.59,5.04,0.51,0.0,2.64,0.0,0.08,...,0.08,2.71,0.40,0.41,0.17,0.13,0.0,0.00,1.54,8.38
3,October 2004,0.40,0.38,9.47,5.29,0.53,0.0,2.76,0.0,0.09,...,0.12,2.91,0.42,0.46,0.12,0.14,0.0,0.00,1.61,8.46
4,November 2004,0.38,0.38,9.48,5.22,0.55,0.0,2.75,0.0,0.07,...,0.12,2.83,0.41,0.44,0.17,0.15,0.0,0.00,1.50,8.21
5,December 2004,0.36,0.37,9.53,5.22,0.53,0.0,2.76,0.0,0.09,...,0.04,2.70,0.39,0.42,0.19,0.12,0.0,0.00,1.45,8.06
6,January 2005,0.39,0.38,9.69,5.23,0.56,0.0,2.65,0.0,0.11,...,0.04,2.91,0.39,0.47,0.15,0.09,0.0,0.00,1.50,7.78
7,February 2005,0.37,0.39,9.86,5.20,0.49,0.0,2.66,0.0,0.07,...,0.05,2.87,0.38,0.45,0.16,0.09,0.0,0.01,1.45,7.65
8,March 2005,0.34,0.37,9.87,5.37,0.45,0.0,2.65,0.0,0.08,...,0.05,2.80,0.42,0.46,0.13,0.11,0.0,0.01,1.44,7.66
9,April 2005,0.34,0.36,9.83,5.41,0.41,0.0,2.55,0.0,0.08,...,0.01,2.77,0.40,0.43,0.14,0.10,0.0,0.01,1.35,7.51

Date
Abap
Ada
C/C++
C#
Cobol
Dart
Delphi/Pascal
Go
Groovy
Haskell
Java
JavaScript
Julia
Kotlin
Lua
Matlab
Objective-C
Perl
PHP
Powershell
Python
R
Ruby
Rust
Scala
Swift
TypeScript
VBA
Visual Basic
0